// src/pages/index/index.vue
<template>
  <Layout>
    <text>{{ msg }}</text>
    <view>
      <nut-button type="primary" @tap="gotoList">主要按钮</nut-button>
    </view>
  </Layout>
</template>

<script setup>
import { ref } from 'vue';
import { useStore } from 'vuex';
import Taro from '@tarojs/taro';
import { getResultDataApi } from '@/services';
import './index.scss';
const store = useStore();
const msg = ref('home page...');
const gotoList = () => {
  store.commit('loadingStart');
  setTimeout(() => {
    store.commit('loadingEnd');
    Taro.navigateTo({
      url: '/pages/list/index'
    });
  }, 1000);
};

getResultDataApi().then(res => {});
</script>

// src/pages/index/index.jsx
import React, { useEffect } from 'react';
import Taro from '@tarojs/taro';
import Layout from '@/components/Layout';
import { View, Text, Button } from '@tarojs/components';
import { useConnect } from '@/store/index';
import { getUsersApi } from '@/services';
import './index.scss';

const Page = props => {
  const { state, dispatch } = useConnect();

  useEffect(() => {
    console.log('componentDidMount');
  }, []);

  const clickHandle = () => {
    dispatch({
      type: 'get_users',
      payload: getUsersApi()
    });
  };

  const gotoListPage = () => {
    Taro.navigateTo({
      url: '/pages/list/index'
    });
  };
  return (
    <Layout>
      {state.users.map(user => {
        return (
          <View className='user' key={user}>
            {user}
          </View>
        );
      })}
      <Button className='button button-primary' onClick={clickHandle}>
        getUsers
      </Button>
      <View>
        <Button className='button button-danger' onClick={gotoListPage}>
          link
        </Button>
      </View>
    </Layout>
  );
};
// Page.options = {
//   addGlobalClass: true
// };
export default Page;
