// src/components/Loading/index.vue
<template>
  <view className="m-loading">
    <view class="lds-ring">
      <view className="ring"></view>
      <view className="ring"></view>
      <view className="ring"></view>
      <view className="ring"></view>
    </view>
  </view>
</template>
<script>
import './index.scss';
export default {
  name: 'Loading'
};
</script>

// src/components/Loading/index.jsx
import React from 'react';
import { View } from '@tarojs/components';
import './index.scss';

const Comp = props => {
  return (
    <View className='m-loading'>
      <View class='lds-ring'>
        <View className='ring'></View>
        <View className='ring'></View>
        <View className='ring'></View>
        <View className='ring'></View>
      </View>
    </View>
  );
};

export default Comp;
